services:
  core-db:
    image: postgres:latest
    container_name: ${DB_CORE_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_CORE_NAME}
    ports:
      - ${DB_CORE_PORT}:${DB_CORE_PORT}

  payment-db:
    image: postgres:latest
    container_name: ${DB_PAYMENT_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_PAYMENT_NAME}
    ports:
      - ${DB_PAYMENT_PORT}:${DB_PAYMENT_PORT}